export const THROTTLE_WINDOW_MS = 60_000;

export const GLOBAL_THROTTLE_LIMIT = 1200;
export const ENDPOINT_THROTTLE_LIMIT = 300;

export const FLASHCARDS_THROTTLE_LIMIT = 1200;
export const AUTH_THROTTLE_LIMIT = 30;
export const AVATAR_UPLOAD_THROTTLE_LIMIT = 20;
